# Generated by Django 2.2.7 on 2019-12-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormDaftar_app_1174043', '0006_auto_20191219_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nomor_Rekening_Bank',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
