# Generated by Django 2.2.7 on 2019-12-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormDaftar_app_1174043', '0008_auto_20191219_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='no_Telepon',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nomor_Rekening_Bank',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
